### ISSUE TITLE
Brak styczności z Pythonem

### ISSUE THREAD

**Issue by kabugh** [realgs/paradygmaty-20#1]
Dzień dobry,

nie miałem z Pythonem zupełnie styczności,
czy można użyć innego języka (Typescript, Scala, Java), czy zadanie to może polega na poznaniu Pythona?

**Comment by realgs** [comment]
pierwsza lista jest po to, by pokazac umiejętności związane z git. już zmieniłem Wam język na scala/java, ale bardzo chętnie zobacze w typescript jak sam zaoferowałeś. Proszę o typescript:)
